version: "3.8"

services:
  mongodb:
    container_name: mongodb3
    image: mongo:latest
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sister
      MONGO_INITDB_ROOT_PASSWORD: sister
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo:/data/db"

